# Claude Code configuration with Nix-managed settings and live-editable config files.
#
# This module:
# - Wraps claude-code to include --mcp-config flag pointing to a live-editable file
# - Generates settings.json with correct paths for the current machine
# - Symlinks other Claude config directories into the nix config repo for live editing
# - Integrates with 1Password shell plugins if enabled
#
# Most config files live in `configs/claude/` and can be edited without rebuilding.
# Exception: settings.json is generated by Nix to interpolate machine-specific paths.
{ config, pkgs, lib, ... }:
let
  inherit (config.lib.file) mkOutOfStoreSymlink;
  inherit (config.home.user-info) nixConfigDirectory;
  claudeDir = "${nixConfigDirectory}/configs/claude";

  # Path where the MCP config will be symlinked (must be absolute for the wrapper)
  mcpConfigPath = "${config.home.homeDirectory}/.claude/mcp.json";

  # Wrap claude-code to include --mcp-config flag
  claude-code-wrapped = pkgs.symlinkJoin {
    name = "claude-code-wrapped";
    paths = [ pkgs.claude-code ];
    buildInputs = [ pkgs.makeWrapper ];
    postBuild = ''
      wrapProgram $out/bin/claude \
        --append-flags "--mcp-config ${mcpConfigPath}"
    '';
    meta.mainProgram = "claude";
  };

  # Settings generated by Nix to interpolate machine-specific paths
  # To modify permissions or plugins, edit this file and rebuild
  settings = {
    "$schema" = "https://json.schemastore.org/claude-code-settings.json";
    permissions.allow = [
      # Tier 1: Read-only git and file inspection
      "Bash(git status:*)"
      "Bash(git diff:*)"
      "Bash(git log:*)"
      "Bash(git branch:*)"
      "Bash(git show:*)"
      "Bash(ls:*)"
      "Bash(cat:*)"
      "Bash(head:*)"
      "Bash(tail:*)"
      # Tier 2: Nix commands
      "Bash(nix build:*)"
      "Bash(nix flake:*)"
      "Bash(nix eval:*)"
      "Bash(nix develop:*)"
      # Tier 3: GitHub CLI read operations
      "Bash(gh pr view:*)"
      "Bash(gh pr list:*)"
      "Bash(gh pr diff:*)"
      "Bash(gh pr checks:*)"
      "Bash(gh issue view:*)"
      "Bash(gh issue list:*)"
    ];
    enabledPlugins = {
      "plugin-dev@claude-plugins-official" = true;
      "commit-commands@claude-plugins-official" = true;
      "frontend-design@claude-plugins-official" = true;
      "feature-dev@claude-plugins-official" = true;
      "pr-review-toolkit@claude-plugins-official" = true;
      "nix-lsp@malos-plugins" = true;
      "json-lsp@malos-plugins" = true;
    };
    extraKnownMarketplaces.malos-plugins.source = {
      source = "directory";
      path = "${claudeDir}/plugins"; # Interpolated per-machine
    };
    additionalDirectories = [ nixConfigDirectory ];
  };
in
{
  # Install wrapped claude-code
  home.packages = [ claude-code-wrapped ];

  # Shell alias for 1Password integration (only if 1Password shell plugins are enabled)
  # --no-masking is a workaround for https://github.com/anthropics/claude-code/issues/7432
  home.shellAliases.claude = lib.mkIf config.programs._1password-shell-plugins.enable
    "op run --no-masking -- claude";

  # Claude config files
  home.file = {
    # Generated by Nix (machine-specific paths)
    ".claude/settings.json".text = builtins.toJSON settings;

    # Symlinked for live editing
    ".claude/CLAUDE.md".source = mkOutOfStoreSymlink "${claudeDir}/CLAUDE.md";
    ".claude/mcp.json".source = mkOutOfStoreSymlink "${claudeDir}/mcp.json";
    ".claude/commands".source = mkOutOfStoreSymlink "${claudeDir}/commands";
    ".claude/skills".source = mkOutOfStoreSymlink "${claudeDir}/skills";
    ".claude/agents".source = mkOutOfStoreSymlink "${claudeDir}/agents";
    ".claude/rules".source = mkOutOfStoreSymlink "${claudeDir}/rules";
    ".claude/hooks".source = mkOutOfStoreSymlink "${claudeDir}/hooks";
  };
}
